//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSZ.OADemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionInfo()
        {
            this.Role = new HashSet<Role>();
            this.R_User_ActionInfo = new HashSet<R_User_ActionInfo>();
            this.Role1 = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public Nullable<int> SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string ActionName { get; set; }
        public string Remark { get; set; }
        public string Controller { get; set; }
        public string ActionMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_User_ActionInfo> R_User_ActionInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role1 { get; set; }
    }
}
