//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSZ.OADemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public int ActionInfoId { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SubBy { get; set; }
        public int Sort { get; set; }
        public bool IsVisable { get; set; }
        public int DialogHeight { get; set; }
        public int DialogWidth { get; set; }
        public string IconUrl { get; set; }
        public int ParentId { get; set; }
    }
}
